services:
  slurmjupyter:
        #image: slurm-jupyter:19.05.5-1
        build: ./jupyter
        hostname: slurmjupyter
        user: admin
        volumes:
                - shared-vol:/home/admin
        ports:
                - 8888:8888
  slurmmaster:
        #image: slurm-master:19.05.5-1
        build: ./master
        hostname: slurmmaster
        user: admin
        volumes:
                - ./apps:/user_apps/admin
                - shared-vol:/home/admin
                - ./certs:/etc/pki/tls/
                - ./master/announcement.yml://etc/ood/config/announcement.yml
                - ./master/announcements.d:/etc/ood/config/announcements.d
                # - ./ood-config:/etc/ood/config:ro
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
                - 80:80
                - 443:443
  slurmnode1:
        privileged: true
        image: slurm-node:19.05.5-1
        build: ./node
        hostname: slurmnode1
        user: admin
        volumes:
                - ./apps:/user_apps/admin
                - shared-vol:/home/admin
        links:
                - slurmmaster
  slurmnode2:
        privileged: true
        image: slurm-node:19.05.5-1
        # build: ./node
        hostname: slurmnode2
        user: admin
        volumes:
                - ./apps:/user_apps/admin
                - shared-vol:/home/admin
        links:
                - slurmmaster
  slurmnode3:
        privileged: true
        image: slurm-node:19.05.5-1
        # build: ./node
        hostname: slurmnode3
        user: admin
        volumes:
                - ./apps:/user_apps/admin
                - shared-vol:/home/admin
        links:
                - slurmmaster
volumes:
        shared-vol:

